# version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: wander_wave_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wander_wave_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9991:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

  # Laravel PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: wander_wave_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel_network

# Volumes for persistence
volumes:
  mysql_data:

# Networks
networks:
  laravel_network:
    driver: bridge
