# Generated by Django 5.0.7 on 2024-07-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='created_by',
        ),
    ]
